export const REQ_START = "REQ_START";
export const CHATLIST_SUCCESS = "CHATLIST_SUCCESS";
export const CHATLIST_FAILURE = "CHATLIST_FAILURE";
export const FETCH_CHATLIST_BY__USER_ID = "FETCH_CHATLIST_BY_USER_ID"