export const REQ_START = "REQ_START";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_FAILURE = "MESSAGE_FAILURE";
export const FETCH_MESSAGE_BY__CHAT_ID = "FETCH_MESSAGE_BY__CHAT_ID"